[theme]
primaryColor = "#FF6F61"            # A vibrant coral color for primary elements
backgroundColor = "#F0F4F8"          # A light grey background
secondaryBackgroundColor = "#FFFFFF" # Pure white for secondary elements
textColor = "#333333"                # Dark text color
font = "sans serif"
