[theme]
# Primary elements (buttons, interactive components)
primaryColor = "#FF6F61"

# Main background
backgroundColor = "#F0F4F8"

# Cards, input fields, expanders
secondaryBackgroundColor = "#FFFFFF"

# Main text color
textColor = "#333333"

# Font settings
font = "sans serif"

# Additional theme settings
base = "light"

# Accent colors
headerColor = "#FF6F61"